name: Hey Firefox Dataset Download
on:
  workflow_dispatch:

jobs:
  dl_dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
          path: auto_train
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install libs
        run: |
          sudo apt-get install ffmpeg
      - name: Install requirements
        run: |
          python -m pip install -r auto_train/requirements.txt
      - name: Download Datasets
        run: |
          python auto_train/scripts/download_hey_firefox.py

      - name: Commit samples
        uses: EndBug/add-and-commit@v9
        with:
          message: hey ff dataset samples
          add: 'dataset_dl/*.wav --force'
          cwd: 'auto_train'
          new_branch: hey_ff_dataset
